#!/bin/bash

### BEGIN INIT INFO
# Provides:          seafile
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs
# Default-Start:     1 2 3 4 5
# Default-Stop:
# Short-Description: Starts Seafile
# Description:       Starts Seafile
### END INIT INFO

function status () {
    if pgrep -f "seafile-controller" 2>/dev/null 1>&2; then
        echo "Seafile is running"
        exit 0
    else
        echo "Seafile is not running"
        exit 1
    fi
}

case $1 in
    "status" )
        status;
        ;;
    * )
        sudo -u {{ config.user }} {{ config.latest }}/seafile.sh $@
        ;;
esac
