#!/bin/bash

### BEGIN INIT INFO
# Provides:          seahub
# Required-Start:    $local_fs $remote_fs $network seafile
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts Seahub
# Description:       Starts Seahub
### END INIT INFO

manage_py=$(readlink -f "{{ config.latest }}")/seahub/manage.py
seahub_sh={{ config.latest }}/seahub.sh

function status () {
    if pgrep -f "${manage_py}" 2>/dev/null 1>&2; then
        return 0
    else
        return 1
    fi
}

function safe_stop () {
    sudo -u {{ config.user }} ${seahub_sh} stop
    while status
    do
        sleep 0.1s
    done
}

case $1 in
    "status" )
        if status ; then
            echo "Seahub is running"
            exit 0
        else
            echo "Seahub is not running"
            exit 1
        fi
        ;;
    "start" )
        sudo -u {{ config.user }} ${seahub_sh} {{ config.seahub_startcmd }}
        ;;
    "stop" )
        safe_stop
        ;;
    "restart" )
        safe_stop
        sudo -u {{ config.user }} ${seahub_sh} {{ config.seahub_startcmd }}
        ;;
    * )
        sudo -u {{ config.user }} ${seahub_sh} $@
        ;;
esac
