#!/bin/bash

### BEGIN INIT INFO
# Provides:          seahub
# Required-Start:    $local_fs $remote_fs $network seafile
# Required-Stop:     $local_fs
# Default-Start:     1 2 3 4 5
# Default-Stop:
# Short-Description: Starts Seahub
# Description:       Starts Seahub
### END INIT INFO

function status () {
    if pgrep -f "manage.py run_gunicorn" 2>/dev/null 1>&2; then
        echo "Seahub is running"
        exit 0
    else
        echo "Seahub is not running"
        exit 1
    fi
}

case $1 in
    "status" )
        status;
        ;;
    "start" )
        sudo -u {{ config.user }} {{ config.latest }}/seahub.sh {{ config.seahub_startcmd }}
        ;;
    * )
        sudo -u {{ config.user }} {{ config.latest }}/seahub.sh $@
        ;;
esac
